### ISSUE TITLE
Unhandled exception in `get_question_stats()`

### ISSUE THREAD

**Issue by hwsamuel** [csu/pyquora#71]
When the `get_question_stats()` method is called with an invalid question, an unhandled exception occurs. Here's a dump of an error:

```python
question = Quora.get_question_stats('Medicine-and-Healthcare')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python2.7/dist-packages/quora/quora.py", line 115, in get_question_stats
return Quora.scrape_question_stats(soup)
File "/usr/local/lib/python2.7/dist-packages/quora/quora.py", line 125, in scrape_question_stats
answer_count = soup.find('div', attrs={'class' : 'answer_count'}).next.split()[0]
AttributeError: 'NoneType' object has no attribute 'next'
```

**Comment by csu** [comment]
Fixed in #72
